services:
    container:
        image: "kohirens/alpine-glibc:dev-${ALPINE_VER}-${GLIBC_VER}"
        build:
            args:
                ALPINE_VER: "${ALPINE_VER}"
                GLIBC_VER: "${GLIBC_VER}"
            dockerfile: "Dockerfile"
            context: "."
            target: "release"
        tty: true
        deploy:
            resources:
                limits:
                    cpus: "2"
