version: "3.8"

services:
    container:
        image: "kohirens/alpine-glibc:${GLIBC_VER:-2.35-r0}"
        build:
            args:
                GLIBC_VER: "${GLIBC_VER}"
            dockerfile: "Dockerfile"
            context: "."
            target: "dev"
        tty: true
